### ISSUE TITLE
Implement comments on frontend

### ISSUE THREAD

**Issue by signalnerve** [bytesizedxyz/nov-project-chirp-frontend#4]
Changes to be implemented:

Comment Structure: { comment: '', chirpId: '' }
HTTP Header - Authorization: "JWT Bearer Token"
POST route: https://nov-chirp-backend.herokuapp.com/chirp/comment/

Client - GET all chirps - returns all chirps and associated comments
Server - modify current GET request to associate all comments with to each chirp

**Comment by maverickg59** [comment]
Changes to be implemented:

Comment Structure: { comment: '', chirpId: '' }
HTTP Header - Authorization: "JWT Bearer Token"
POST route: https://nov-chirp-backend.herokuapp.com/chirp/comment/

Client - GET all chirps - returns all chirps and associated comments
Server - modify current GET request to associate all comments with to each chirp
